export const SCHEMA_NOT_REGISTERED = 'SCHEMA_NOT_REGISTERED'

export const IMPLICIT_SELECT_ALL_NOT_ALLOWED = 'IMPLICIT_SELECT_ALL_NOT_ALLOWED'

export const ROLE_DOES_NOT_HAVE_ACCESS_HOOK_LEVEL =
  'ROLE_DOES_NOT_HAVE_ACCESS_HOOK_LEVEL'

export const ROLE_DOES_NOT_HAVE_ACCESS_HANDLER_LEVEL =
  'ROLE_DOES_NOT_HAVE_ACCESS_HANDLER_LEVEL'
